# Generated by Django 4.2.5 on 2023-09-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=24)),
                ('executive_board', models.BooleanField(default=False)),
                ('ima_board', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('isbn', models.CharField(blank=True, max_length=64, null=True, verbose_name='ISBN')),
                ('isbn_10', models.CharField(blank=True, max_length=64, null=True, verbose_name='ISBN-10')),
                ('publising_date', models.DateTimeField()),
                ('is_ebook', models.BooleanField(default=False, verbose_name='Ebook')),
                ('autors', models.ManyToManyField(to='main.connection')),
            ],
        ),
    ]
