# Generated by Django 4.2.5 on 2023-09-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='autors',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='literature',
            old_name='publising_date',
            new_name='publishing_date',
        ),
    ]
