# Generated by Django 4.2.5 on 2023-09-28 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_literature_is_book_literature_is_cd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='literature_images/'),
            preserve_default=False,
        ),
    ]
