# Generated by Django 4.2.5 on 2023-09-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_editabletext_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=248)),
                ('description', models.TextField(blank=True, max_length=2048)),
                ('pdf', models.FileField(upload_to='archive/pdf/')),
            ],
        ),
    ]
