# Generated by Django 4.2.5 on 2023-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
