# Generated by Django 3.2.9 on 2023-12-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_archive_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='main.Tag'),
        ),
    ]
