# Generated by Django 3.2.9 on 2024-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_archive_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='tag',
            field=models.ManyToManyField(blank=True, to='main.Tag'),
        ),
    ]
