# Generated by Django 4.2.5 on 2024-01-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_connection_is_admin_alter_connection_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ISBN-13'),
        ),
    ]
