# Generated by Django 4.2.5 on 2024-02-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_literature_isbn_13'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditableText',
        ),
        migrations.DeleteModel(
            name='Literature',
        ),
        migrations.DeleteModel(
            name='LiteratureTag',
        ),
    ]
